# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heisen
email: info@heisenhub.com
description: > # this means to ignore newlines until "baseurl:"
  Сообщество Heisen объединяет активных людей. Мы хотим делиться опытом и учиться новому.
  Мы быстро растем и самостоятельно решаем любые задачи.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://heisenhub.com" # the base hostname & protocol for your site, e.g. http://example.com
address: 3503 Jack Northrop Ave Suite AH761 Hawthorne, CA 90250
phone: +7 (985) 128-37-08
twitter_username: vlterno
github_username:  vlterno

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

teamates:
  - name:       Evgeni Bikov
    display:    Женя
    avatar:     ../images/team/Evgeni_Bikov.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Vladimir Ternovykh
    display:    Вова
    avatar:     ../images/team/Vladimir_Ternovykh.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Andrey Tarkhov
    display:    Андрей
    avatar:     ../images/team/Andrey_Tarkhov.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Vitaly Pavlenko
    display:    Виталий
    avatar:     ../images/team/Vitaly_Pavlenko.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Gleb Voropaev
    display:    Глеб
    avatar:     ../images/team/Gleb_Voropaev.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Mark Vinogradov
    display:    Марк
    avatar:     ../images/team/Mark_Vinogradov.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Dmitriy Andreev
    display:    Дима
    avatar:     ../images/team/Dmitriy_Andreev.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Pavel Reutov
    display:    Павел
    avatar:     ../images/team/Pavel_Reutov.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Yann Pavlenko
    display:    Ян
    avatar:     ../images/team/Yann_Pavlenko.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Artem Gaydukov
    display:    Артем
    avatar:     ../images/team/Artem_Gaydukov.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Dmitriy Shubenok
    display:    Дима
    avatar:     ../images/team/Dmitriy_Shubenok.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Alexandr Kosicin
    display:    Саша
    avatar:     ../images/team/Alexandr_Kosicin.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Artem Alekseev
    display:    Артём
    avatar:     ../images/team/Artem_Alekseev.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Ilyans Nugaev
    display:    Ильянс
    avatar:     ../images/team/Ilyans_Nugaev.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Kseniya Borisovskaya
    display:    Ксения
    avatar:     ../images/team/Kseniya_Borisovskaya.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Mihail Shestopalov
    display:    Михаил
    avatar:     ../images/team/Mihail_Shestopalov.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Nadezhda Gapeeva
    display:    Надежда
    avatar:     ../images/team/Nadezhda_Gapeeva.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Nurbek Kuspanov
    display:    Нурбек
    avatar:     ../images/team/Nurbek_Kuspanov.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Olga Podolceva
    display:    Ольга
    avatar:     ../images/team/Olga_Podolceva.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Vyacheslav Ivanchenko
    display:    Слава
    avatar:     ../images/team/Vyacheslav_Ivanchenko.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Yuriy Markin
    display:    Юрий
    avatar:     ../images/team/Yuriy_Markin.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Alena Egorova
    display:    Алёна
    avatar:     ../images/team/Alena_Egorova.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Girls
    display:    + 9 девушек
    avatar:     ../images/team/avatar_woman.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none
    hashtags:   none
    skills:     none
    slack:      none

  - name:       Boys
    display:    + 71 парень
    avatar:     ../images/team/avatar_man.png
    twitter:    none
    vk:         none
    fb:         none
    projects:   none
    cv:         none
    github:     none
    email:      none
    phone:      none

partners:
  - name:       Skoltech
    logo:       images/partners/skoltech.png
    website:    none
    description: >
      &#171;The mission of Skoltech is to educate students, advance knowledge, and foster innovation 
      in order to address critical scientific, technological, and innovation challenges and gaps facing Russia 
      and the world.&#187;

  - name:       ObjectLab
    logo:       images/partners/objectlab.png
    website:    none
    description: >
      &#171;Мы — команда профессионалов в сфере разработки новых продуктов, промышленного дизайна. 
      Мы открыты к сотрудничеству с компаниями, стартапами или дизайнерами желающими выпустить свой продукт,
      выжав из него максимум возможностей!&#187; 

  - name:       Inspector Cloud
    logo:       images/partners/inspectorcloud.png
    website:    none
    description: >
      &#171;Онлайн-платформа аудита торговых точек. Объективная и актуальная информация о товарах на полках 
      помогает брендам и ритейлерам повысить продажи.&#187; 

  - name:       Notion
    logo:       images/partners/notionso.png
    website:    none
    description: >
      &#171;Docs, Wikis, Tasks. Seamlessly in One. A unified workspace for modern teams.&#187; 

navigation:
  - text:       О нас 
    url:        /    
  - text:       Команда 
    url:        /team/
  - text:       Партнеры
    url:        /partners/