version: '2.2'
services:
  redis:
    image: redis:alpine
    command: redis-server --bind 0.0.0.0
    ports:
     - 6379:6379
  web:
    env_file: .env
    ports:
     - 5000:5000
    volumes:
     - /tmp:/tmp
     - /tmp/static:/code/static
    build: .
    depends_on:
     - redis