# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
