# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('displayed_name', models.CharField(max_length=200)),
                ('slack_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('cv_link', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=200)),
            ],
        ),
    ]
