# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20161019_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slack_avatar',
            field=models.CharField(default='', max_length=400),
        ),
    ]
