# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_person_slack_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giver', to='team.Person')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='team.Person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='thanks',
            field=models.ManyToManyField(through='team.Thank', to='team.Person'),
        ),
    ]
