# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_person_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='progress',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.Progress'),
        ),
    ]
