# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20161031_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='thanked',
            field=models.BooleanField(default=False),
        ),
    ]
