# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20161114_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='persons',
            field=models.ManyToManyField(related_name='tags', to='team.Person'),
        ),
    ]
