# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20161031_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='child_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Tag'),
        ),
    ]
