# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='task_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
