# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_person_rating'),
        ('tasks', '0002_reaction_task_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_rating', models.IntegerField(default=0)),
                ('task_progress', models.IntegerField(default=0)),
                ('project_value', models.IntegerField(default=0)),
                ('photo_penalty', models.IntegerField(default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.Person')),
            ],
        ),
    ]
