# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_progress_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
